### ISSUE TITLE
Store cookies between the requests

### ISSUE THREAD

**Issue by briskajanis1** [Ganesan-Chandran/vscode-fetch-client#1]
Hello,

Would it be possible to implement a feature to store the response cookies between different requests - similar to Postman? 
The use case would be when you have and api which uses cookies for user authorisation and you first log in, the cookies get stored and passed along with all the subsequent requests to the api.

**Comment by Ganesan-Chandran** [comment]
Hi @briskajanis1 
Thank you for your feedback. Will add into features list.

**Comment by Ganesan-Chandran** [comment]
This feature has added in [Fetch Client v1.1.0](https://github.com/Ganesan-Chandran/vscode-fetch-client/releases/tag/v1.1.0)

Please update the Fetch Client and let me know if you have any queries/feedback.

Thanks :-)
