### ISSUE TITLE
Sync request into workspace

### ISSUE THREAD

**Issue by usarral** [Ganesan-Chandran/vscode-fetch-client#10]
**Describe the solution you'd like**
Could be very usefull the option to save the request in the workspace, without need to make an export all time. Like this all team can sync the request avoiding lost endpoints
**Describe alternatives you've considered**
Make an export on push

**Comment by egorovsa** [comment]
Confirm .It was working good in Thunder client before they required a subscription.
Pls. This feature is really necessary!

**Comment by Ganesan-Chandran** [comment]
Hi @usarral and @egorovsa 

Thank you for using the Fetch Client extension. This feature has added in the latest version [Fetch Client v1.5.1](https://github.com/Ganesan-Chandran/vscode-fetch-client/releases/tag/v1.5.1)

Please update the Fetch Client and let me know if you have any queries/feedback.

@egorovsa Thank you for your contribution. I have done few changes on top of your code with my PR.

![image](https://github.com/user-attachments/assets/5222d836-5e70-4eba-a5a8-dd1ce2bfa99a)

Please update the **_Fetch Client_** and restart the VS Code. Go to the **_Fetch Client_** settings and select this option.

**DON'T ENTER ANY VALUE** in the below settings. It is automatically done by Fetch Client.

![image](https://github.com/user-attachments/assets/5ac38505-3452-4279-ac3a-f74cbce4701c)
