### ISSUE TITLE
Set the request dimension limit of get or post visualization configurable and not limited to 5 Mbytes

### ISSUE THREAD

**Issue by FrancoTampieri** [Ganesan-Chandran/vscode-fetch-client#11]
**Is your feature request related to a problem? Please describe.**
Sometimes I have some requests under 10 Mbytes and I would like to see it. Many times when I try to download the result the file is everytime empty.

**Describe the solution you'd like**
I would like if is possible to setup the limit of the download and show of the reponse, normally I opened with vscode file of 10 Gbytes of dimension without problem.

**Describe alternatives you've considered**
Fix the download of the file to prevent to have empty file

**Screenshots**
This is the problem
![Screenshot 2024-05-07 alle 15 30 40](https://github.com/Ganesan-Chandran/vscode-fetch-client/assets/4396444/ac973c1a-6965-4ab6-ac4d-00de664a555d)

When I save the file
![Screenshot 2024-05-07 alle 15 32 08](https://github.com/Ganesan-Chandran/vscode-fetch-client/assets/4396444/86acdcf1-1020-49d0-bed7-0a2dd955783d)

![Screenshot 2024-05-07 alle 15 32 58](https://github.com/Ganesan-Chandran/vscode-fetch-client/assets/4396444/5f14d22d-d0fb-46f3-a262-ad77b2d4c513)

this is the result an empty content
![Screenshot 2024-05-07 alle 15 33 40](https://github.com/Ganesan-Chandran/vscode-fetch-client/assets/4396444/de0b60a6-82ce-4fe4-a58f-6a58ed103f1f)

**Comment by Ganesan-Chandran** [comment]
Hi @FrancoTampieri 

Thank you for using the Fetch Client extension. This feature has added in the latest version [Fetch Client v1.5.1](https://github.com/Ganesan-Chandran/vscode-fetch-client/releases/tag/v1.5.1)

Please update the Fetch Client and let me know if you have any queries/feedback.

Please update the **_Fetch Client_** and restart the VS Code. Go to the **_Fetch Client_** settings and select this option.

![image](https://github.com/user-attachments/assets/c160a8a7-2466-402b-b3d5-8c2aacd3d224)
