### ISSUE TITLE
Highlight variables

### ISSUE THREAD

**Issue by sviatcraft** [Ganesan-Chandran/vscode-fetch-client#3]
I would like to see the variable, that I use, highlighted.

![image](https://user-images.githubusercontent.com/62302382/173940520-b61130fc-bed4-4230-84e1-26264f72167d.png)

**Comment by Ganesan-Chandran** [comment]
Hi @sviatcraft , 

Thanks for your feedback and will add this feature in coming release.

**Comment by Ganesan-Chandran** [comment]
This feature has added in [Fetch Client v1.1.0](https://github.com/Ganesan-Chandran/vscode-fetch-client/releases/tag/v1.1.0)

Please update the Fetch Client and let me know if you have any queries/feedback.

Thanks :-)
