### ISSUE TITLE
Clicking on collection item opens a new window every time instead of switching to existing window

### ISSUE THREAD

**Issue by markcarroll** [Ganesan-Chandran/vscode-fetch-client#6]
**Describe the bug**
Clicking on a request in the collection list causes a new window to open with an empty request instead of switching to a previously opened window.  If this is intended behavior it would be good to have an option to switch it.  

**To Reproduce**
1. Click on a request in a collection, new window opens up
2. Click on a different window
3. Click on the same request in the same collection
4. Another new window opens up

**Expected behavior**
The first window should re-activate. 

Great plug-in, by the way.

**Comment by Ganesan-Chandran** [comment]
Hi @markcarroll 

Thanks you for using the Fetch Client extension. This feature has added in [Fetch Client v1.4.0](https://github.com/Ganesan-Chandran/vscode-fetch-client/releases/tag/v1.4.0)

Please update the Fetch Client and let me know if you have any queries/feedback.
