### ISSUE TITLE
import/export postman collections and environment

### ISSUE THREAD

**Issue by ghost** [Ganesan-Chandran/vscode-fetch-client#7]
It would be nice to have an option to import/export postman collections and environment

**Comment by Ganesan-Chandran** [comment]
Hi @StephaneBonilla 

Thanks you for using the Fetch Client extension. This feature (import postman collection) has added in [Fetch Client v1.4.0](https://github.com/Ganesan-Chandran/vscode-fetch-client/releases/tag/v1.4.0)

Please update the Fetch Client and let me know if you have any queries/feedback.
