### ISSUE TITLE
POST method not properly set just after creating new Http Request in a collection

### ISSUE THREAD

**Issue by syracine69** [Ganesan-Chandran/vscode-fetch-client#8]
**Describe the bug**
Changing the HTTP method to POST just after creating new request in Request form doesn't set it to correct value.

**To Reproduce**
1. Go to Fetch Client extension by clicking the left icon in VSCode
2. Click on Collection tab
3. Click on '...' button to the right of the collection name in left panel. Then select in the menu 'New Request'
4. Enter the name of new request in the top line input. Then type Enter
5. The new Request is created in the left panel with the HTTP GET method.
6. In the right panel, change HTTP method dropdown to POST
7. Type CTRL+S to save the change.
8. The method in left panel is still 'GET'
9. Fill the information in the right panel to create de HTTP request
10. Suppose that you use a backend framework for your API, set the allowed method to POST (e.g. routes files for PHP Laravel Framework)
11. Send the request with Fetch-client
12. The response returned an HTTP "405 Error - Method not allowed" showing that GET method was used to send the request
13. That is the bug

**Expected behavior**
Do not returns an HTTP 405 Error when backend route allows only HTTP POST method.

**Screenshots**
![image](https://github.com/Ganesan-Chandran/vscode-fetch-client/assets/53153173/e7c8e6a4-dacd-4b08-a7ae-38d294c548fa)

**Desktop (please complete the following information):**
 - OS: Windows 10, build 19045.3324 (22H2)
 - Fetch Client Version 1.3.0
 - VS Code Version 1.81.1

**Additional context**
I show that there are many tabs opened in Fetch-Client extension view with the same HTTP request. Maybe that is the bug
I have been installed the Thunder Client extension and it enabled. Hope that there is no conflict with Fetch-content extension

**Comment by Ganesan-Chandran** [comment]
Hi @syracine69 

Thank you for using the Fetch Client extension. This issue is fixed in the latest version [Fetch Client v1.5.1](https://github.com/Ganesan-Chandran/vscode-fetch-client/releases/tag/v1.5.1)

Please update the Fetch Client and let me know if you have any queries/feedback.
